import type { Metadata } from 'next';
import { Geist, Geist_Mono, Urbanist, Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';
import SubscribeSection from '@/components/subscribe/SubscribeSection';
import { BookingProvider } from '@/hooks/BookingContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const urbanist = Urbanist({
  variable: '--font-urbanist',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${urbanist.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <BookingProvider>
          {children}
          <SubscribeSection />
        </BookingProvider>
        <Footer />
      </body>
    </html>
  );
}
